# Generated by Django 4.2.3 on 2023-09-04 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(validators=[django.core.validators.MaxValueValidator(7)])),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='Password must be at least 8 characters long.'), django.core.validators.MaxLengthValidator(limit_value=128, message='Password cannot exceed 128 characters.'), django.core.validators.RegexValidator(message='Password must contain at least one lowercase letter, one uppercase letter, one digit, and one special character.', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=!]).*$')])),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(validators=[django.core.validators.MaxValueValidator(7)])),
            ],
        ),
    ]
