# Generated by Django 4.2.3 on 2023-09-05 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(validators=[django.core.validators.MaxValueValidator(300000)])),
                ('firstname_and_middlename', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=10)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(65)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='Password must be at least 8 characters long.'), django.core.validators.MaxLengthValidator(limit_value=128, message='Password cannot exceed 128 characters.'), django.core.validators.RegexValidator(message='Password must contain at least one lowercase letter, one uppercase letter, one digit, and one special character.', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@#$%^&+=!]).*$')])),
                ('confirmpass', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
