# Generated by Django 4.2.3 on 2023-09-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_registered_delete_admin_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
