# Generated by Django 4.2.3 on 2023-09-11 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
