# Generated by Django 4.2.3 on 2023-09-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_extenduser_delete_adminregister_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='lastname',
        ),
    ]
