# Generated by Django 4.2.3 on 2023-09-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_extenduser_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
