# Generated by Django 4.2.3 on 2023-09-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_extenduser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
