# Generated by Django 4.2.3 on 2023-10-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_extenduser_first_name_extenduser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
