# Generated by Django 4.2.3 on 2023-10-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_extenduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='employee_mahindra',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
