# Generated by Django 4.2.3 on 2023-10-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_extenduser_employee_mahindra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='user',
        ),
    ]
