# Generated by Django 4.2.3 on 2023-10-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.DurationField(default=None),
        ),
    ]
