# Generated by Django 4.2.3 on 2023-10-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_attendance_total_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timein',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timeout',
            field=models.TimeField(null=True),
        ),
    ]
