# Generated by Django 4.2.3 on 2023-10-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_attendance_timein_alter_attendance_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='overtime',
            field=models.IntegerField(default=None),
        ),
    ]
