# Generated by Django 4.2.3 on 2023-10-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_attendance_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='overtime',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
