# Generated by Django 4.2.3 on 2023-10-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_extenduser_first_name_extenduser_last_name'),
        ('logs', '0007_alter_attendance_overtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.extenduser'),
        ),
    ]
