# Generated by Django 4.2.3 on 2023-10-20 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_attendance_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='employee',
            new_name='employee_key',
        ),
    ]
