# Generated by Django 4.2.3 on 2023-10-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_rename_employee_attendance_employee_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='overtime',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timein',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='timeout',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_hours',
            field=models.IntegerField(default='0'),
        ),
    ]
