# Generated by Django 4.2.3 on 2023-10-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='month',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='year',
            field=models.IntegerField(default='0'),
        ),
    ]
